version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - franquicia-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: franquicias
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: una_contraseña_muy_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - franquicia-network

volumes:
  postgres_data:

networks:
  franquicia-network:
    driver: bridge
